# This is a basic workflow to help you get started with Actions

name: EncryptionTestResults
   
# Controls when the workflow will run
on:
      workflow_dispatch:
    

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Zip Readme file
        run: |
          zip -r readme.zip README.md

      - name: Echo de gpg version
        run: |
          echo gpg -version


    - name: Encrypts file using the license plate as pwd
      run: |
          gpg -c --passphrase ${{secrets.LICENSEPLATE}} -o encrypt.gpg readme.zip


    - name: Send email
      uses: dawidd6/action-send-mail@v3
      with:
        # Required mail server address:
        server_address: ${{secrets.MAIL_SERVER}}
        # Required mail server port:
        server_port: 465
        # Optional (recommended): mail server username:
        username: ${{secrets.MAIL_USERNAME}}
        # Optional (recommended) mail server password:
        password: ${{secrets.MAIL_PASSWORD}}
        # Required mail subject:
        subject: Github Actions test job result
        # Required recipients' addresses:
        to:  ${{secrets.MAIL_ADDRESS}}
        # Required sender full name (address can be skipped):
        from: ${{secrets.MAIL_USERNAME}}
        # Optional plain body:
        body: Build job of ${{github.repository}} completed successfully! Decryp the attachment with the command `gpg -d --passphrase $myPWD  encrypt2.gpg > caca10.txt` where $myPWD is your license plate
        # Optional attachments:
        attachments: readme.zip 
    

