# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Run Encryption routine of test results

env:
      LICENSE_PLATE: ${{ secrets.MY_LICENSE_PLATE }} 
      BASEURL:   ${{ secrets.BASEURL }} 
      
on:
    workflow_dispatch:
    
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - TEST_NAME: "Latest v2"
            AWS_CLI_VERSION: "2"
     #    - TEST_NAME: "Specific v2"
     #      AWS_CLI_VERSION: "2.0.30"
     #    - TEST_NAME: "Latest v1"
     #      AWS_CLI_VERSION: "1"
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Add key
      run: |
           wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
    
    - name: Set repo
      run: |
           echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
    



          
    - name: Zip Readme file
      run: |
          zip -r readme.zip README.md
    

  - name: Echo de gpg version
      run: |
          echo 'gpg -version'



    - name: Encrypts file using the license plate as pwd
      run: |
          gpg -c --passphrase ${{secrets.LICENSEPLATE}} -o encrypt.gpg readme.zip


    - name: Send email
      uses: dawidd6/action-send-mail@v3
      with:
        # Required mail server address:
        server_address: ${{secrets.MAIL_SERVER}}
        # Required mail server port:
        server_port: 465
        # Optional (recommended): mail server username:
        username: ${{secrets.MAIL_USERNAME}}
        # Optional (recommended) mail server password:
        password: ${{secrets.MAIL_PASSWORD}}
        # Required mail subject:
        subject: Github Actions test job result
        # Required recipients' addresses:
        to:  ${{secrets.MAIL_ADDRESS}}
        # Required sender full name (address can be skipped):
        from: ${{secrets.MAIL_USERNAME}}
        # Optional plain body:
        body: Build job of ${{github.repository}} completed successfully! Decryp the attachment with the command `gpg -d --passphrase $myPWD  encrypt2.gpg > caca10.txt` where $myPWD is your license plate
        # Optional attachments:
        attachments: readme.zip 
    

