name: runLambda

on:
  workflow_dispatch:
  
jobs: 
  runs_Lambda_function:
    name: Invoke foobarFunction Lambda
    runs-on: ubuntu-22.04
    
    steps:
      - name: invokes function
        id: foobar
        uses: gagoar/invoke-aws-lambda@master
    
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: ca-central-1
          FunctionName: getFullSnapshot
          Payload: '{ "myParameter": false }'


      - name: Store response payload to file
        run: echo '${{ fromJSON(steps.foobar.outputs.response).Payload }}' > invocation-response.json